### PR TITLE
1045-Rename-Seaside-Pharo-Core-into-Seaside-Squeak-Core-and-Seaside-Pharo20-Core-into-Seaside-Pharo-Core

### LINKED ISSUE #1045: Rename Seaside-Pharo-Core into Seaside-Squeak-Core and Seaside-Pharo20-Core into Seaside-Pharo-Core
Because Pharo 1 is not maintained anymore and the only Smalltalk loading Seaside-Pharo-Core is Squeak. 

Subissue of #1044 (I prefer multiple steps since it impacts multiple smalltalks)

### PR DESCRIPTION
**Pull request by jecisc**
Rename Seaside-Pharo-Core into Seaside-Squeak-Core and Seaside-Pharo20-Core into Seaside-Pharo-Core.

Because Pharo 1 is not maintained anymore and the only Smalltalk loading Seaside-Pharo-Core is Squeak.

Fixes #1045

### CODE REVIEW

**Comment by jecisc** [comment]
Arf, is Seaside still metadatafull?

**Comment by jecisc** [comment]
Squeak is failing but it was already failing.

**Comment by jecisc** [comment]
Johan told me we do not care about metadatas anymore so this PR should be right.

**Comment by jbrichau** [comment]
@jecisc I notice you also already changed package extension names, so the PR now has more conflicts than before. I took care to avoid changing the packages `*Pharo` and `*Pharo20` but had not yet looked into the changes here in detail.

No problem, I will merge or re-do the PR manually.

**Comment by jbrichau** [comment]
Merged manually in 96235f92f0cdc30eb289c54780b446246de91f95

**Pull request closed without merging**
