### PR TITLE
Release 3.4.0

### PR DESCRIPTION
**Pull request by jbrichau**

### CODE REVIEW

**Comment by jbrichau** [comment]
The github-travisci integration seems to be broken, though builds are being triggered but they are not being reported back here. So here it is: https://travis-ci.org/github/SeasideSt/Seaside/builds/674365020

**Comment by jbrichau** [comment]
@marschall Hi Philippe, can you hit the review button of your liking on this PR?
thanks!

**Comment by jbrichau** [comment]
Hi @marschall 
Do you have any thoughts to release or not? I thought that it was about time to get the work that was done out of the door, but wanted to get your opinion on it.
Thanks!

**Comment by marschall** [comment]
Sorry, yeah go ahead. Thank you for pushing this.

**Pull request merged**
