### PR TITLE
Add an Open button to open the webbrowser from control panel

### PR DESCRIPTION
**Pull request by astares**
Add an "Open" button to Seaside adapter control panel to quicky open a WebBrowser on the adapter itself

### CODE REVIEW

**Comment by astares** [comment]
screenshot from 2018-12-20 01-30-10

**Comment by astares** [comment]
Pharo 4 will not have git anyway, no?

**Comment by jecisc** [comment]
Seaside is still loadable in pharo 4.

You don’t have Iceberg but FileTree still work.

**Comment by astares** [comment]
Is this really a use case? Johan will convert to Tonel so we have Windows back on track once an issue with Tonel converter is sorted out.

Do we really have known users of P4 with FileTree?

**Comment by jecisc** [comment]
Filetree will stay for a while because Squeak does not have a tonel support anyway and the repo is also for squeak.

**Comment by astares** [comment]
@jecisc   It's a change in "Seaside-Pharo-Tools-Spec", not a Squeak one if I'm not mistaken.

**Comment by jecisc** [comment]
Yes but we can't have one package in tonel format and the others in filetree.

**Comment by astares** [comment]
Agree - but we will have a branch with Tonel

**Comment by jecisc** [comment]
I think that the goal is not to split the development into two branches and to have differences between the two of them.

**Comment by astares** [comment]
I guess the idea is to keep the development in file tree for now (until the rest catches up) - but nonetheless provide tonel converted versions (at least for the releases) so it could be loaded on Windows.

**Comment by jecisc** [comment]
Yes, so the code should be the same between both, else it will make it really hard to sync.

**Comment by jbrichau** [comment]
@astares I moved this PR to merge into master when accepted. I did not take a look at the code but I agree with @jecisc comments that the code should do feature detection so that it only gets added when the `WebBrowser` class is present.

**Comment by theseion** [comment]
@astares Can you make the requested change?

**Comment by theseion** [comment]
The new Spec2 based control panel includes such an open button. Closing this PR in favor of #1155 .

**Comment by astares** [comment]
👍

**Pull request closed without merging**
