### PR TITLE
Fix for issue #1129

### PR DESCRIPTION
**Pull request by jbrichau**
Deal with ZnUrl pathSegments change in [1] where instances of Charact…er can be part of the path segments. Keep backwards compatibility with previous Zinc versions as well by converting to strings when creating a WAUrl instance.

[1] https://github.com/svenvc/zinc/commit/d962746ae9688550d0c826b9103018a87789afb1

### CODE REVIEW

**Comment by noha** [comment]
I guess this won‘t work with deliberate slashes in a url aka %2F The decoded slash will be stored as #/ in a segment. Only the trailing slash becomes $/

**Comment by jbrichau** [comment]
@noha I just adapted the existing code to work again in the presence of Character instances because I anticipate this error will soon occur when people load latest Zinc (or install Seaside).

Not sure if we need to cover additional cases in there. For that, I'm not sure why we were filtering them out anyway (yet).

**Comment by jbrichau** [comment]
@marschall I put you as reviewer because I wanted some of your thoughts on why we explicitly filter the trailing slash out. If you do not have the time, no worries, then I merge this PR asap because current Seaside breaks with latest Zinc.

**Comment by marschall** [comment]
I wonder whether something like this would be easier to understand and less error prone

```
	zincUrl hasPath ifTrue: [
		zincUrl isDirectoryPath
			ifTrue: [
				"last path segment is $/ or #/"
				zincUrl pathSegments allButLastDo: [ :each |
					seasideUrl addToPath: each ].
				seasideUrl slash: true ]
			ifFalse: [
				seasideUrl addAllToPath: zincUrl pathSegments ] ].
```
if we don't care about the copy we could even use something like this

```
	zincUrl hasPath ifTrue: [
		| segments |
		segments := zincUrl isDirectoryPath
			ifTrue: [ zincUrl pathSegments allButLast "last path segment is $/ or #/" ]
			ifFalse: [ zincUrl pathSegments ].
		seasideUrl addAllToPath: segments.
		seasideUrl slash: zincUrl isDirectoryPath ].
```

**Pull request merged**
