### PR TITLE
Use #greaseAsByteArray when computing etag

### LINKED ISSUE #1383: Squeak does not have an implementation of Integer>>#asByteArray
`WAAbstractFileLibrary>>#entityTagFor:` sends `#asByteArray` to a `LargePositiveInteger`, which causes and MNU in Squeak. This causes errors when accessing jQuery files (no styling visible on pages).

I've come up with a quick fix version but it lacks VM support as in Pharo:

```smalltalk
asByteArray

	| stream |
	stream := ByteArray new writeStream.
	((self numberOfDigitsInBase: 2) / 8) ceiling to: 1 by: -1 do: [:digitIndex |
		stream nextPut: (self digitAt: digitIndex)].
	^ stream contents
```

### PR DESCRIPTION
**Pull request by theseion**
Fixes #1383

### CODE REVIEW

**Comment by theseion** [comment]
This PR depends on https://github.com/SeasideSt/Grease/pull/161.

**Comment by jbrichau** [comment]
As soon as the mentioned PR is merged and we also get the [GsDevKit/Grease](https://github.com/GsDevKit/grease) mirror synced (necessary for GemStone builds), we can merge this one.

**Comment by jbrichau** [comment]
Created the PR to also update Grease in GsDevkit/GLASS: https://github.com/GsDevKit/Grease/pull/28

**Comment by theseion** [comment]
Pharo-12: a new deprection that heavily impacts Monticello causes timeouts.
Others: unrelated test failures.

**Comment by timrowledge** [comment]
Just to catch up a little, Squeak 6.1 now has #asByteArray for LargePositiveIntegers. Prior versions would simply need to use sometihng akin to 

`^theBigNumber as: ByteArray`

**Comment by theseion** [comment]
Thanks. I'm surprised you got it in after the discussions I saw on the mailing list 😉.

**Review by jbrichau — APPROVED** [review]

**Pull request merged**
