### PR TITLE
Adds CORS filter and Functional test

### PR DESCRIPTION
**Pull request by eMaringolo**
I implemented a basic CORS filter with a functional test (including setting up a separate server adaptor to handle cross-origin requests).

It would be great to merge this into the upcoming release, so it can be ported to VAST (and other dialects).

### CODE REVIEW

**Comment by eMaringolo** [comment]
This solves #1270

**Comment by eMaringolo** [comment]
@jbrichau Can this be merged? :-)

**Comment by jbrichau** [comment]
> @jbrichau Can this be merged? :-)

Sorry for the unresponsiveness. I'm swimming in too much things at once. I will test this hopefully this week!

**Comment by jbrichau** [comment]
@eMaringolo I did not notice before that the Gemstone builds are failing here. This is probably because of incompatibility. We will need to fix this before this can be merged.

**Comment by eMaringolo** [comment]
@jbrichau But the incompatibility is caused by something else, right? Looking at the job details, the failing tests have nothing to do with my proposed changes, or do they?

**Comment by jbrichau** [comment]
The failing tests are `testSentButNotImplemented` and `testUndefinedSymbols`. These tests fail because there is code added that sends unimplemented messages and references undefined symbols. 

I'm guessing it's in the example code, which is not part of a test so no other tests will fail.

`expandMacrosWith:` is probably the unimplemented message in GemStone.

**Comment by jbrichau** [comment]
@eMaringolo I merged this in a branch to be able to debug and fix the broken tests in GemStone.

**Pull request merged**
