### PR TITLE
Add Squeak support for selectorOfPragma: to make the REST route initi…

### PR DESCRIPTION
**Pull request by timrowledge**
…alisation work

### CODE REVIEW

**Comment by timrowledge** [comment]
Johan, after much help from tcj it appears we made a proper pull request. Please let me know if there are still any problems!

**Comment by jbrichau** [comment]
Well.. the changes are still in the Seaside-REST-Core package and not in specific package for Squeak. (see https://github.com/SeasideSt/Seaside/pull/1309/files)

**Comment by timrowledge** [comment]
This is another attempt - this time the github stuff claims the package is Seaside-Squeak-REST-Core so maybe it will work ?

**Comment by timrowledge** [comment]
I've pushed buttons again and maybe this time got them in the right order? Sorry this is taking so much effort for one lousy line of code!

> On 2022-05-01, at 8:21 AM, Johan Brichau ***@***.***> wrote:
> 
> 
> Well.. the changes are still in the Seaside-REST-Core package and not in specific package for Squeak. (see https://github.com/SeasideSt/Seaside/pull/1309/files)
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.
> 


tim
--
tim Rowledge; ***@***.***; http://www.rowledge.org/tim
Strange OpCodes: KFP: Kindle Fire in Printer

**Comment by jbrichau** [comment]
@timrowledge
The code in the PR now contains a Seaside-Squeak-REST-Core package with the implementation of `selectorOfPragma:` but it also still contains the changes to Seaside-REST-Core package.

In addition, I noticed in the `BaselineOfSeaside3` that the Seaside-Pharo-REST-Core package was being included for Squeak. Therefore, I created a new PR #1313 which also transfers the code in the Seaside-Pharo-REST-Core package to the Seaside-Squeak-REST-Core package and adapts the BaselineOfSeaside3 accordingly.

Therefore I close this PR and will merge #1313

**Comment by timrowledge** [comment]
Johan, thank you very much for helping with this. I have no idea how all the mix-ups came to be; it's hard to imagine how a single one-line method can cause so much trouble.

> On 2022-05-22, at 6:22 AM, Johan Brichau ***@***.***> wrote:
> 
> 
> @timrowledge
> The code in the PR now contains a Seaside-Squeak-REST-Core package with the implementation of selectorOfPragma: but it also still contains the changes to Seaside-REST-Core package.
> 
> In addition, I noticed in the BaselineOfSeaside3 that the Seaside-Pharo-REST-Core package was being included for Squeak. Therefore, I created a new PR #1313 which also transfers the code in the Seaside-Pharo-REST-Core package to the Seaside-Squeak-REST-Core package and adapts the BaselineOfSeaside3 accordingly.
> 
> Therefore I close this PR and will merge #1313
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.
> 


tim
--
tim Rowledge; ***@***.***; http://www.rowledge.org/tim
 Falling slowly, softly falling, the chiasmus collapses to the bar floor.

**Comment by timrowledge** [comment]
> On 2022-05-01, at 8:21 AM, Johan Brichau ***@***.***> wrote:
> 
> 
> Well.. the changes are still in the Seaside-REST-Core package and not in specific package for Squeak. (see https://github.com/SeasideSt/Seaside/pull/1309/files)

I'm baffled.

What was in my image, the one we did the attempted commit from, was 


!GRSqueakPlatform methodsFor: '*seaside-squeak-rest-core' stamp: 'tpr 1/13/2022 18:13'!
selectorOfPragma: aPragma

	^aPragma keyword! !

To add to the irritation, that method no longer exists in my image, but who knows what caused that extra insanity?

Buried in the depths of my file system I see  Seaside-fork/repository/Seaside-REST-Core.package/GRSqueakPlatform.extension/instance/selectorOfPragma..st which is presumably why the pull request sees it in the Seaside-REST-Core package.


tim
--
tim Rowledge; ***@***.***; http://www.rowledge.org/tim
Useful random insult:- Can easily be confused with facts.

**Pull request closed without merging**
