### PR TITLE
1053-Simplify-gettext-baseline

### PR DESCRIPTION
**Pull request by jecisc**
Since Pharo is the only one using gettext, merge Seaside-Gettext-Core and Seaside-Pharo-Gettext-Core
+ Simplify baseline

### CODE REVIEW

**Comment by jecisc** [comment]
Fixes #1053

**Comment by jbrichau** [comment]
I should check, because there is a gettext for Gemstone (we're using that one in Yesplan).
Dunno why it got slipped from the baseline...

**Comment by jecisc** [comment]
Maybe it is in an external project as it is now in Pharo?

**Comment by jecisc** [comment]
Oh I see that here we load the external project and have a compatibility package for Seaside for it. So it's probably not that.

**Comment by jecisc** [comment]
Any news on this?

**Comment by jbrichau** [comment]
Gettext is on my radar (because it's broken right now); but I'm trying to devote my spare time for Seaside to the website now.

**Comment by jbrichau** [comment]
@jecisc Changed the base to master, but I think we can just close this one when I (or someone) address gettext

**Comment by jbrichau** [comment]
Closing this PR as I'm fixing it on the gettext branch (which is to be merged when gettext upstream change has merged)

**Pull request closed without merging**
