### PR TITLE
Adding pragma selector for Squeak per Tim Rowledge. Grease issue #132

### PR DESCRIPTION
**Pull request by tcj**
My attempt to use Squeak to submit @timrowledge 's fileout discussed in [Grease issue #132](https://github.com/SeasideSt/Grease/issues/132)

I suspect my PR might not be accepted because of all the metadata changes unfortunately included...?

### CODE REVIEW

**Comment by jbrichau** [comment]
The method should be added to a platform-specific package that only gets loaded in Squeak. Adding the method to the core package is loading it into all platforms. Therefore, this PR is not how it can work.

 Take a look at how this is done for Pharo. There is a package Seaside-Pharo90-REST-Core. Load that into Squeak, rename it and change the method implementations to make it work in Squeak. Publish that package and submit the PR.

Preferably, also add the package to the BaselineOfSeaside3, but I can assist there if you want.

**Comment by tcj** [comment]
OK.  Thanks Johan.

Since this is a little more involved, I'd like to run tests before/after. 
But the 'Tests' group in the 'common' spec includes 
'Seaside-Tests-Parasol' now, and I had trouble getting Parasol to load in 
Squeak.  So, to test in Squeak might require some extra work.

**Comment by timrowledge** [comment]
Well, I've added a Seaside-Squeak-REST-Core package with the one extension method. For some reason when I went to save it the package that got saved looks like it was 'Seaside-Squeak-Core-tpr.2" which is not what I expected. You may want to delete that.

Trying again...OK this time it saved the package I expected - Seaside-Squeak-REST-Core-tpr.1 is now apparently in the SeasideSt/Seaside:master/repository.

I hope that actually helps...

> On 2022-01-15, at 8:34 AM, Tim Johnson ***@***.***> wrote:
> 
> 
> OK. Thanks Johan.
> 
> Since this is a little more involved, I'd like to run tests before/after. 
> But the 'Tests' group in the 'common' spec includes 
> 'Seaside-Tests-Parasol' now, and I had trouble getting Parasol to load in 
> Squeak. So, to test in Squeak might require some extra work.
> 
> 
> On Fri, 14 Jan 2022, Johan Brichau wrote:
> 
> > 
> > The method should be added to a platform-specific package that only gets loaded
> > in Squeak. Adding the method to the core package is loading it into all
> > platforms. Therefore, this PR is not how it can work.
> > 
> > Take a look at how this is done for Pharo. There is a package
> > Seaside-Pharo90-REST-Core. Load that into Squeak, rename it and change the
> > method implementations to make it work in Squeak. Publish that package and
> > submit the PR.
> > 
> > Preferably, also add the package to the BaselineOfSeaside3, but I can assist
> > there if you want.
> > 
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > Triage notifications on the go with GitHub Mobile for iOS or Android.
> > You are receiving this because you authored thethread.[AARP4V25AH5MWFZQLY6TYNLUWELDVA5CNFSM5MAHITK2YY3PNVWWK3TUL52HS4DFVREXG4
> > 3VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOHRVLWIQ.gif] Message ID:
> > ***@***.***>
> > 
> > 
> >
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you were mentioned.
> 


tim
--
tim Rowledge; ***@***.***; http://www.rowledge.org/tim
Useful random insult:- Can't find log base two of 65536 without a calculator.

**Comment by jbrichau** [comment]
I don’t see a change in the branch of this pull request. Maybe this was committed to another branch or only locally? Anyway, Since the changes that are already in this branch need to be reverted, I suggest creating a new branch and a new PR.

It would also be better if all required extensions are added rather than the single method. As I mentioned, the easiest way would be to load the Pharo package, rename it, fix the code for Squeak compatibility and publish the package to (a branch of) the repository.

**Comment by timrowledge** [comment]
I'm a bit puzzled by the process here and maybe that is what is causing problems. I don't use git and haven't ever had need to use metacello beyond trivial install stuff.

I created  a new package 'Seaside-Squeak-REST-Core'  containing the single method that we need to add, and appear to have successfully saved it to the repository
Screen Shot 2022-01-16 at 12 42 28 PM

However, I see no sign at all of it on the git repository page. I have no idea why that might be. What do I need to do to get this worked out so you can review it etc?

**Comment by tcj** [comment]
Tim:  very roughly, you have to (1) fork the Seaside repo, (2) clone it to 
your local computer, (3) add that local repo as a filetree:// repo in the 
MC browser, (4) 'save' your changes to the package to that repo, being 
very careful not to include unchanged methods in the MC commit window, (5) 
run `git add` and `git commit` and `git push`, (6) open up the pull 
request URL in a web browser and fill its form and submit.

That's very rough.  It's time-consuming and complex.

**Comment by tcj** [comment]
Oh, I forgot to mention (3.5) create a local branch in your fork.

**Comment by jbrichau** [comment]
Friendly reminder that the method extension should be in a Squeak only package. I recommend creating `Seaside-Squeak-REST-Core`. Take a look at how this is done for other platforms regarding platform-specific methods. Seaside was built to explicitly support this.

Until then, this PR is not mergeable.

**Comment by timrowledge** [comment]
I truly thought I had created an appropriate Seaside-Squeak-REST-Core package here. It is after all what the MC browser showed me in my jan 16 comment here...

Best I can think of is to hope that maybe tcj can spare a moment to talk and  help me through the git lunacy.

**Comment by tcj** [comment]
Hi @timrowledge  — for sure.  Let's find a time.  I will email you.

**Comment by tcj** [comment]
Closing this in favor of #1309

**Pull request closed without merging**
