### PR TITLE
1086-Rename-Seaside-Tests-Pharo-Core-to-Seaside-Tests-Sqeak-Core-and-Seaside-Tests-Pharo40-Core-to-Seaside-Tests-Pharo-Core

### LINKED ISSUE #1086: Rename Seaside-Tests-Pharo-Core to Seaside-Tests-Sqeak-Core and Seaside-Tests-Pharo40-Core to Seaside-Tests-Pharo-Core
Because now Seaside-Tests-Pharo-Core is only loaded in Squeak and Seaside-Tests-Pharo40-Core in Pharo.

### PR DESCRIPTION
**Pull request by jecisc**
Rename Seaside-Tests-Pharo-Core to Seaside-Tests-Sqeak-Core and Seaside-Tests-Pharo40-Core to Seaside-Tests-Pharo-Core

+ Some other cleanings

Fixes #1086

### CODE REVIEW

**Comment by jecisc** [comment]
The Pharo 7 failure is not related. One of the latest Pharo change broke SmalltalkCI.

**Comment by theseion** [comment]
Could you move the additional changes that you did (e.g. in Seaside-Tests-Pharo-Core) to a new PR? I'd like this PR to only contain the package renaming and removal. Otherwise it makes it hard to track down errors.

**Comment by jecisc** [comment]
To make things easier to review I'll split the PR in two because I should not have included the deletion of Seaside-Tests-Pharo20-Core and Seaside-Pharo20-Tools-Web in this PR.

**Comment by jecisc** [comment]
Done: https://github.com/SeasideSt/Seaside/pull/1089

**Comment by theseion** [comment]
You're right. It looked like you had made changes but that's just because the new package has the same name as the old one but now has different content.

**Pull request merged**
