### PR TITLE
CORS Filter

### PR DESCRIPTION
**Pull request by jbrichau**
#1274 to master

### CODE REVIEW

**Comment by jbrichau** [comment]
@eMaringolo I fixed the code for Gemstone and added an automated test for the CORS filter. 

The starting of the additional adaptor for the tests needs to be different for Gemstone. I’ll take a look later, and if it proves too difficult, we will mark it an expected failure for Gemstone.

**Comment by eMaringolo** [comment]
Thank you @jbrichau, I don't have a GemStone environment to make any change or running the tests.

**Comment by jbrichau** [comment]
@eMaringolo I'm fiddling with the testcase I made for it using Parasol. I want to make the test work in GemStone and will finish it asap. Then we're of for release 3.4.6!

**Comment by jbrichau** [comment]
@eMaringolo I had to fix the CORSFilter for GemStone because `String>>join:` does not exist in GemStone.

I also finally was able to get the testing to work and now... the github CI actions are failing to execute the tests for some reason or another... sigh, sometimes it sucks doing software development....

**Comment by eMaringolo** [comment]
Thank you @jbrichau , next time I won't create any functional test that causes this much trouble! 😂

**Pull request merged**
