### PR TITLE
Adapt baseline to Pharo 7.

### PR DESCRIPTION
**Pull request by jecisc**

### CODE REVIEW

**Comment by jecisc** [comment]
Close issue #978

**Comment by jbrichau** [comment]
I merged the PR#980 for dev branch, but it shows we hit another issue in https://github.com/Metacello/metacello/issues/476 
Holding off merging this for master when that's fixed

**Comment by svenvc** [comment]
I just tried to load Seaside 3.2 (GitHub.1516790362) in Pharo 7 (Pharo-7.0+alpha.build.493.sha.d53a70bc946ed83b046f61ac35f00c67fa77269a (32 Bit)) with the changes proposed here and at least the load and some quick testing with ZnZincSeasideAdaptor seems to indicate no direct problems.

Why don't we integrate this so that others can load Seaside 3.2 in Pharo 7 too ?

This is really important to make progress, IMHO.

**Comment by jbrichau** [comment]
I can try again but we did hit issues: https://travis-ci.org/SeasideSt/Seaside/jobs/313946580
So, the load now works?

**Comment by svenvc** [comment]
With the modifications described here (just add a couple of #'pharo7.x' tags here and there) the load worked. I did see the same error first, but not with the modified baseline loaded. I did do this load interactively, not as a CI build, using:
````
Metacello new
 baseline:'Seaside3';
 repository: 'github://SeasideSt/Seaside:master/repository';
 load.
````

**Comment by jbrichau** [comment]
I'll take another look but Seaside builds on SmalltalkCI are failing for Pharo 7, so as long as this is the case, we cannot reliably move to Pharo7. Now, I understand we should at least make it load and I will merge now.

**Comment by jbrichau** [comment]
Copied the changes of this PR in 3c7efa6500cf945efdad9455544979bdc3288736

**Comment by jecisc** [comment]
@jbrichau There was more changes than this.

**Comment by jecisc** [comment]
There was also: baselinejavascript..st, baselinerest..st and baselineslime..st

**Comment by jbrichau** [comment]
@jecisc Yeah, noticed it too. Thanks for watching. I added another commit.
Mind that the `load: 'CI'` does not work because of a DNU on `Pragma`, so this needs to change as well if we want a build.

**Pull request closed without merging**
