### PR TITLE
Reference Grease v1.4.x

### PR DESCRIPTION
**Pull request by jbrichau**
See #1126

### CODE REVIEW

**Comment by jecisc** [comment]
Travis is green, the change seems good to me.

**Comment by jvalteren** [comment]
Guys, since this change, I'm getting a `Revspec 'v1.4.x' not found` error when loading my own project baseline with a dependency on baseline Seaside3 (at github://SeasideSt/Seaside:master/repository).
When I debug and move waaaay down the stack (am I the only one finding Metacello/Iceberg stacks impossible to read?), I can find the following signal message text:

> You already have an Iceberg repository 
at /Users/jvalteren/Documents/Pharo/images/p7-papertrail/pharo-local/iceberg/SeasideSt/Grease.

What can cause this? I haven't specified any dependencies on Grease.

**Comment by jbrichau** [comment]
Not sure, but I'm guessing your local clone of Grease did not fetch the new tag. Do you get this on a new full load?

**Comment by jvalteren** [comment]
Forgive me, for I was wrong ;-) It turned out that it was indeed having a repository conflict on the local filesystem.

It looks like I have uncovered a severe bug in the Pharo launcher. It seems to set the working of any new image to directory of a previous image, which effectively makes Iceberg share its repository location (because the 'pharo-local' of the other image is being used as repository location).

I will create an issue at the pharo-launcher project.

**Comment by jvalteren** [comment]
PS Grease now does show a `Detached HEAD` status under Iceberg repositories...

**Comment by jecisc** [comment]
It’s normal, because you have checkout a tag and not a branch. So you have a working version of grease, but if you wish to contribute to it, you need to checkout (or create) a branch first. 

For your comment on the share local directory, it might not be a problem of the launcher but of the settings. If you have exported all Pharo settings, it includes a fix location of a local directory, so all images launched with settings will point to this directory.

**Pull request merged**
