### PR TITLE
Add ETag support for file library

### LINKED ISSUE #1324: Add ETag support for file library
ETags are useful for those who serve (static) content from the image in deployment environments. Caching proxies / CDN use the value of the etag with a `If-None-Match` header allowing the server to send 304.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag
https://support.cloudflare.com/hc/en-us/articles/218505467-Using-ETag-Headers-with-Cloudflare

### PR DESCRIPTION
**Pull request by marschall**
Fixes #1324

### CODE REVIEW

**Comment by marschall** [comment]
Requires https://github.com/SeasideSt/Grease/pull/140

**Comment by jbrichau** [comment]
The annoying situation here is that GemStone uses `https://github.com/GsDevKit/Grease` instead of the SeasideSt/Grease... which is why the tests are still failing (at least). 
Will do the PR to GsDevKit to ping Dale.

**Comment by astares** [comment]
Any update on this?

**Comment by jbrichau** [comment]
> Any update on this?

I will take a look why the tests are failing for GemStone

**Review by jbrichau — APPROVED** [review]

**Pull request merged**
